# Generated by Django 5.0.6 on 2024-06-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
