# Generated by Django 5.0.6 on 2024-07-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tickets_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
