# Generated by Django 5.0.6 on 2024-07-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tickets_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='is_booked',
        ),
    ]
