# Generated by Django 5.0.6 on 2024-07-01 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_tickets_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
